apiVersion: v1
kind: Service
metadata:
  name: react-application
  labels:
    run: react-application
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    run: react-application