apiVersion: v1
kind: Service
metadata:
  name: bff-backoffice-svc
spec:
  selector:
    app: bff-backoffice
  type: NodePort
  ports:
    - name: http-bff-backoffice
      port: 80
      targetPort: 3001
